name: .NET Runtime OpenSSL 3.5 CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout .NET Runtime
      uses: actions/checkout@v4
      with:
        repository: dotnet/runtime
        path: runtime

    - name: Checkout OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        path: openssl
        ref: openssl-3.5

    - name: Build OpenSSL
      run: |
        cd $GITHUB_WORKSPACE/openssl
        ./Configure -shared --prefix=/opt/openssl --openssldir=/opt/openssl
        make -j 4
        sudo make install_sw


    - name: Build .NET
      run: |
        cd $GITHUB_WORKSPACE/runtime
        ./eng/common/native/install-dependencies.sh
        ./build.sh -rc release -s clr+libs