name: .NET Runtime OpenSSL 3.5 CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout .NET Runtime
      uses: actions/checkout@v4
      with:
        repository: dotnet/runtime
        path: runtime

    - name: Checkout OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        path: openssl
        ref: openssl-3.5