name: .NET Runtime OpenSSL 3.5 CI

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
    inputs:
      openssl_ref:
        type: string
        description: openssl/openssl Branch
        required: true
        default: 'openssl-3.5'
      runtime_ref:
        type: string
        description: dotnet/runtime Branch
        required: true
        default: 'main'
  push:
    paths:
      - '.github/workflows/ci.yml'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout .NET Runtime
      uses: actions/checkout@v4
      with:
        repository: dotnet/runtime
        path: runtime
        ref: ${{ inputs.runtime_ref || 'main' }}

    - name: Checkout OpenSSL
      uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        path: openssl
        ref: ${{ inputs.openssl_ref || 'openssl-3.5' }}

    - name: Build OpenSSL
      run: |
        cd $GITHUB_WORKSPACE/openssl
        ./Configure -shared --prefix=/opt/openssl --openssldir=/opt/openssl
        make -j 4
        sudo make install_sw

    - name: Build .NET
      env:
        LD_LIBRARY_PATH: /opt/openssl/lib64
        OPENSSL_ROOT_DIR: /opt/openssl
      run: |
        cd $GITHUB_WORKSPACE/runtime
        sudo ./eng/common/native/install-dependencies.sh
        ./build.sh -rc release -s clr+libs /p:NativeOptimizationDataSupported=false

    - name: .NET Cryptography Tests
      env:
        LD_LIBRARY_PATH: /opt/openssl/lib64
        OPENSSL_ROOT_DIR: /opt/openssl
      run: |
        cd $GITHUB_WORKSPACE/runtime
        ./dotnet.sh test src/libraries/System.Security.Cryptography/tests
        SSC_RESULT=$?
        ./dotnet.sh test src/libraries/Microsoft.Bcl.Cryptography/tests
        MBC_RESULT=$?

        echo "SSC_RESULT: $SSC_RESULT; MBC_RESULT: $MBC_RESULT"

        if [ $SSC_RESULT -ne 0 ] || [ $MBC_RESULT -ne 0 ]; then
          exit 1
        else
          exit 0
        fi

    - name: Upload Test Results
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v4
      with:
        path: |
          ${{ github.workspace }}/runtime/artifacts/bin/System.Security.Cryptography.Tests/Debug/net10.0-unix/TestResults/
          ${{ github.workspace }}/runtime/artifacts/bin/Microsoft.Bcl.Cryptography.Tests/Debug/net10.0/TestResults/
        if-no-files-found: warn
        retention-days: 7

    - name: Open Failure Issue
      if: ${{ failure() }}
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.create({
            owner: "vcsjones",
            repo: "runtime-ci",
            title: "Build Failure for run ${{ github.run_id }}",
            body: "There was a CI build failure. Go look at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          });
